# Generated by Django 5.1.3 on 2025-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro_id', models.IntegerField()),
                ('cargo', models.CharField(max_length=50)),
                ('equipe', models.CharField(max_length=20)),
                ('dataIni', models.DateField()),
                ('dataFim', models.DateField()),
            ],
        ),
    ]
