# Generated by Django 5.1.3 on 2025-02-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cargo_membro',
            table='Cargo_Membro',
        ),
    ]
