# Generated by Django 5.1.3 on 2025-02-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cargo_membro_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo_membro',
            options={'managed': False},
        ),
    ]
